export const ADD_APP_PROGRESS = 'ADD_APP_PROGRESS';
export const REMOVE_APP_PROGRESS = 'REMOVE_APP_PROGRESS';

export const GET_DOCTORS_REQUEST = 'GET_DOCTORS_REQUEST';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
