export const ADD_APP_PROGRESS = 'ADD_APP_PROGRESS';
export const REMOVE_APP_PROGRESS = 'REMOVE_APP_PROGRESS';

export const GET_DOCTORS_REQUEST = 'GET_DOCTORS_REQUEST';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';

export const GET_RECORDS_REQUEST = 'GET_RECORDS_REQUEST';
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';
export const ADD_RECORD = 'ADD_RECORD';

export const GET_DOCTOR_BUSY_DATES_REQUEST = 'GET_DOCTOR_BUSY_DATES_REQUEST';
export const GET_DOCTOR_BUSY_DATES_SUCCESS = 'GET_DOCTOR_BUSY_DATES_SUCCESS';

export const GET_DOCTOR_DATE_INTERVALS_SUCCESS = 'GET_DOCTOR_DATE_INTERVALS_SUCCESS';

export const GET_SAVE_RECORD_REQUEST = 'GET_SAVE_RECORD_REQUEST';
export const GET_SAVE_RECORD_SUCCESS = 'GET_SAVE_RECORD_SUCCESS';

export const CLOSE_MODAL_SAVE_RECORD = 'CLOSE_MODAL_SAVE_RECORD';

export const CHANGE_DOCTOR_RECORD_FIELD_VALUE = 'CHANGE_DOCTOR_RECORD_FIELD_VALUE';
export const CLEAR_DOCTOR_RECORD = 'CLEAR_DOCTOR_RECORD';
