export const ADD_APP_PROGRESS = 'ADD_APP_PROGRESS';
export const REMOVE_APP_PROGRESS = 'REMOVE_APP_PROGRESS';

export const GET_DOCTORS_REQUEST = 'GET_DOCTORS_REQUEST';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';

export const GET_DOCTOR_DATE_INTERVALS_SUCCESS = 'GET_DOCTOR_DATE_INTERVALS_SUCCESS';

export const GET_SAVE_RECORD_REQUEST = 'GET_SAVE_RECORD_REQUEST';
export const GET_SAVE_RECORD_SUCCESS = 'GET_SAVE_RECORD_SUCCESS';

export const CHANGE_DOCTOR_RECORD_FIELD_VALUE = 'CHANGE_DOCTOR_RECORD_FIELD_VALUE';
export const CLEAR_DOCTOR_RECORD = 'CLEAR_DOCTOR_RECORD';
